### ISSUE TITLE
Widgets don't reset

### ISSUE THREAD

**Issue by hobgoblina** [albertvaka/bettercounter#68]
Widgets for counters that reset daily aren't resetting properly. So, for example, if I had a count of 1 yesterday, the widget will still say 1 today... and then when I tap on it the timestamp will update but the count still says 1 since that's today's count. It can be pretty confusing both when looking at the count and when tapping on it, leading to double counts that I then have to go into the app to correct.

**Comment by albertvaka** [comment]
Good catch, I'll take a look and try to fix this when I have time.

**Comment by albertvaka** [comment]
The fix doesn't seem to be working, reopening.

**Comment by albertvaka** [comment]
Should be fixed now.

**Comment by hobgoblina** [comment]
seems like this issue is still happening for me on 4.9.1

**Comment by FreeWillDeveloper** [comment]
> Widgets for counters that reset daily aren't resetting properly. So, for example, if I had a count of 1 yesterday, the widget will still say 1 today... and then when I tap on it the timestamp will update but the count still says 1 since that's today's count. It can be pretty confusing both when looking at the count and when tapping on it, leading to double counts that I then have to go into the app to correct.

I am using the latest compiled version 4.9.3, and this problem still exists. I have to restart the app each time for the widget to update the data.

**Comment by albertvaka** [comment]
v4.9.4 has another attempt to fix this, let me know if it does once you get the update :)
